config/routes.rb
Rails.application.routes.draw do
    resources :pages, only: %i[index] do
        get :contacts, on: :collection
        get :blog, on: :collection
    end

    root to: 'pages#index'
end

app/models/application_record.rb
# Base model class
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index; end

    def contacts; end

    def blog; end
end

app/helpers/application_helper.rb
# Base helper
module ApplicationHelper
    def google_map
        "https://maps.googleapis.com/maps/api/staticmap?center=51.8308762,19.9166485&size=640x430&zoom=10"
    end
end

app/views/layouts/application.html.slim
doctype html
html lang='en'
    head
        meta charset='utf-8'
        meta name='viewport' content='width=device-width, initial-scale=1.0'
        title Delegowanie
        = stylesheet_link_tag 'application'
        = javascript_include_tag 'application'
        = csrf_meta_tag
    body
        == yield

app/views/pages/about.slim
- provide(:path, 'about')
= render 'shared/nav_logo'
section.text_block
    .row
        .columns.medium-8
            .main_article.about
                .title Tytul
                .photo= image_tag 'article_main.jpg'
                .text.bold Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                h3 Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                h3 Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                .date Jan Kowalski | 23.2017
    .row
        .columns.small-12.about_block
            h2 Powiazane artykuly:
            .other_articles.about
                .article
                    .photo= image_tag 'article.jpg'
                    .title Tytul
                    .text Lorem ipsum dolor
                    .date 23.2017
                .article
                    .photo= image_tag 'article.jpg'
                    .title Tytul
                    .text Lorem ipsum dolor
                    .date 23.2017
                .article
                    .photo= image_tag 'article.jpg'
                    .title Tytul
                    .text Lorem ipsum dolor
                    .date 23.2017
            .buttons
                .button= link_to 'Poprzednie', '#'
                .button= link_to 'Nastepne', '#'
= render 'shared/footer'
= render 'shared/uslugi'

app/views/pages/blog.slim
- provide(:path, 'about')
= render 'shared/mobile_nav'
= render 'shared/nav_logo'
.blog
    section.text_block
        .row
            .columns.medium-8
                .main_article.about
                    .title Tytul
                    .photo= image_tag 'article_main.jpg'
                    .text.bold Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                    .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                    .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                    h3 Lorem ipsum dolor
                    .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                    h3 Lorem ipsum dolor
                    .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                    .date Jan Kowalski | 23.2017
        .row
            .columns.small-12.about_block
                h2 Powiazane artykuly:
                .other_articles.about
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 1', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 2', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 3', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
= render 'shared/footer'
= render 'shared/uslugi'

app/views/pages/contacts.slim
- provide(:path, 'contacts')
= render 'shared/mobile_nav'
= render 'shared/nav_logo'
.contacts
    section.text_block.small
        .row
            .columns.medium-8.large-6
                .block
                    h1
                        | Uslugi skrojone
                        br /
                        | na miare 
                        span Twoich potrzeb!
                    p Kompleksowa obsluga firm delegujacych pracownikow za granice oraz zatrudniajacych cudzoziemcow.
    section.banner_block
        .row
            .columns.medium-10.large-8
                .text.bold Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
                .text Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor Lorem ipsum dolor
    section.text_block.small
        .row
            .columns.medium-10.medium-offset-1.large-8.large-offset-2
                .with_map
                    h3 Petna Nazwa Kancelarii
                    .block
                        p Address
                    .block
                        p +48 123 456 789
                        p kancelaria@delegowanie.pl
                    #map.map
                        = image_tag 'staticmap.png'
= render 'shared/footer'
= render 'shared/uslugi'

app/views/pages/index.slim
= render 'shared/mobile_nav'
#index.banner
    .row
        .columns.medium-8.large-6.banner_column
            .main_logo= link_to 'Delegowanie24', root_path
            .block
                h1
                    | Usługi skrojone
                    br /
                    | na miarę 
                    span Twoich potrzeb!
                p Kompleksowa obsługa firm delegujących pracowników za granicę oraz zatrudniających cudzoziemców.
                button.button.white data-open='uslugi' Poznaj usługi
    = render 'shared/nav'
section.text_block
    .row
        .columns.medium-7.large-8
            #blog.main_article
                .title Tytul 1
                .date 23.2017
                .photo= link_to image_tag('article_main.jpg'), blog_pages_path
                .text Lorem ipsum dolor
                .button= link_to 'Czytaj dalej', blog_pages_path
            .other_articles
                .main_part
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 1', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 2', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 3', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article 
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 4', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                .hidden_part
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 1', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 2', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 3', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
                    .article 
                        .photo= link_to image_tag('article.jpg'), blog_pages_path
                        .title= link_to 'Tytul 4', blog_pages_path
                        .text Lorem ipsum dolor
                        .date 23.2017
            .buttons
                .button= link_to 'Wszystkie', '#', id: 'wszystkie'
        .columns.medium-5.large-4
            .right_block
                /.block.editors
                    h2 Redaktorzy:
                    .editor
                        .image= image_tag 'editor.png'
                        .name Joanna Kowalska
                    .editor
                        .image= image_tag 'editor.png'
                        .name Joanna Kowalska
                    .editor
                        .image= image_tag 'editor.png'
                        .name Joanna Kowalska
                .block.media
                    h2 Social media:
                    = link_to image_tag('facebook.png'), '#'
                    = link_to image_tag('linkedin.png'), '#'
                .block.contacts
                    h2 Kontakt
                    .half
                        p +48 123 456 789
                        p lorem@ipsum.pl
                    .half
                        p Address
= render 'shared/footer'
= render 'shared/uslugi'

app/views/shared/_footer.slim
footer
    .row
        .columns.medium-6
            p.white &copy; copyright Delegowanie.pl
        .columns.medium-6
            p.right
                | Strategia, realizacja, wsparcie 
                span Tomczak | Stanislawski

app/views/shared/_mobile_nav.slim
nav.mobile_nav
    .title-bar data-responsive-toggle='example-menu'
        button.menu-icon type='button' data-toggle='example-menu'
        .title-bar-title= link_to 'Delegowanie24', root_path
    .top-bar#example-menu
        .top-bar-left
            ul.menu.vertical.medium-horizontal
                li= link_to 'Main page', root_path
                li= link_to 'Kontakt', contacts_pages_path
                li= link_to 'Blog', root_path(anchor: 'logo'), class: 'blog'
                

app/views/shared/_nav.slim
#logo.nav.no_logo name='logo'
    .row
        .columns.small-12
            nav
                ul
                    li
                        button.button.from_menu data-open='uslugi' Usługi
                    li= link_to 'Kontakt', contacts_pages_path, class: "#{'active' if yield(:path) == 'contacts' }"
                    li= link_to 'Blog', root_path(anchor: 'logo'), class: 'blog'
                .links
                    = link_to image_tag('facebook.png'), '#'
                    = link_to image_tag('linkedin.png'), '#'
                .languages
                    = link_to 'PL', '#', class: 'active'
                    = link_to 'EN', '#'
                    = link_to 'DE', '#'
                .call
                    = link_to image_tag('call.png'), '#'
                .phone
                    .tel +48 123 456 789
                    .email kontakt@delegowanie24.pl
            .name
                .logo= link_to 'Delegowanie24', root_path
                ul
                    li
                        button.button.from_menu data-open='uslugi' Usługi
                    li= link_to 'Kontakt', contacts_pages_path, class: "#{'active' if yield(:path) == 'contacts' }"
                    li= link_to 'Blog', root_path(anchor: 'logo'), class: 'blog'

app/views/shared/_nav_logo.slim
.nav
    .row
        .columns.small-12
            nav
                ul
                    li
                        button.button.from_menu data-open='uslugi' Uslugi
                    li= link_to 'Kontakt', contacts_pages_path, class: "#{'active' if yield(:path) == 'contacts' }"
                    li= link_to 'Blog', root_path(anchor: 'logo'), class: 'blog'
                .links
                    = link_to image_tag('facebook.png'), '#'
                    = link_to image_tag('linkedin.png'), '#'
                .languages
                    = link_to 'PL', '#', class: 'active'
                    = link_to 'EN', '#'
                    = link_to 'DE', '#'
                .call
                    = link_to image_tag('call.png'), '#'
                .phone
                    .tel +48 123 456 789
                    .email kontakt@delegowanie24.pl
            .name
                .logo= link_to 'Delegowanie24', root_path

app/views/shared/_nav_nologo.slim
.nav.no_logo_popup
    .row
        .columns.small-12
            nav
                .links
                    = link_to image_tag('facebook.png'), '#'
                    = link_to image_tag('linkedin.png'), '#'
                .languages
                    = link_to 'PL', '#', class: 'active'
                    = link_to 'EN', '#'
                    = link_to 'DE', '#'
                .call
                    = link_to image_tag('call.png'), '#'
                .phone
                    .tel +48 123 456 789
                    .email kontakt@delegowanie24.pl
            .name
                ul
                    li
                        button.button.from_menu data-open='uslugi' Usługi
                    li= link_to 'Kontakt', contacts_pages_path, class: "#{'active' if yield(:path) == 'contacts' }"
                    li= link_to 'Blog', root_path(anchor: 'logo'), class: 'blog'

app/views/shared/_uslugi.slim
#uslugi.reveal.full data-reveal=''
    .row
        .main_logo= link_to 'Delegowanie24', root_path
    #uslugies.row
        .blocks
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
            .block
                = link_to 'Transgraniczne delegowanie pracownikow', '#'
    #second_popup.row
        .banner_uslugi
            h2 Transgraniczne delegowanie pracownikow
            .row
                .columns.medium-7
                    p Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
                    ul
                        li Lorem ipsum Lorem ipsum
                        li Lorem ipsum Lorem ipsum
                        li Lorem ipsum Lorem ipsum
                        li Lorem ipsum Lorem ipsum
                .columns.medium-4.medium-offset-1
                    h3 Zaproszenie do kontaktu lorem ipsum dolor sit amet cons
                    .name Jan Kowalski
                    .tel +48 123 456 789
                    .email jan.kowalski@delegowanie24.pl
            .button.wroc.white= link_to 'Wroc', root_path, id: 'wroc'
    = render 'shared/nav_nologo'
    button.close-button aria-label=('Close modal') data-close='' type='button'
        span aria-hidden='true' &times;